animal_classifier/urls.py
from django.urls import path
from . import views

app_name = "animal_classifier"

urlpatterns = [
    path('', views.predict_animal, name="predict_animal"),
]

common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views as common_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', common_views.home, name='home'),

    # app urls
    path('flower/', include('flower_classifier.urls')),
    path('animal/', include('animal_classifier.urls')),
    # path('fruit/', include('fruit_classifier.urls')),
    path('human_emotion/', include('human_emotion_classifier.urls')),
    path('vehicle/', include('vehicle_classifier.urls')),
    path('digit/', include('digit_classifier.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digit_classifier/urls.py
from django.urls import path
from . import views

app_name = "digit_classifier"

urlpatterns = [
    path('', views.predict_digit, name="predict_digit"),
]

flower_classifier/urls.py
from django.urls import path
from . import views

app_name = "flower_classifier"

urlpatterns = [
    path('', views.predict_flower, name="predict_flower"),
]

vehicle_classifier/urls.py
from django.urls import path
from . import views

app_name = "vehicle_classifier"

urlpatterns = [
    path('', views.predict_vehicle, name="predict_vehicle"),
]

common/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

common/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}Image Classifier{% endblock %}</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="bg-gray-100 min-h-screen text-gray-900">
  <div class="max-w-4xl mx-auto p-6">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

common/templates/home.html
{% extends "base.html" %} {% block title %}Home - Image Classifier{% endblock %}
{% block content %}
<div class="max-w-4xl mx-auto mt-10">
  <h1 class="text-3xl font-bold mb-6 text-center">Image Classifier Projects</h1>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <a
      href="{% url 'flower_classifier:predict_flower' %}"
      class="p-4 bg-white rounded shadow hover:shadow-lg transition"
    >
      🌸 Flower Classifier
    </a>
     <a
      href="{% url 'animal_classifier:predict_animal' %}"
      class="p-4 bg-white rounded shadow hover:shadow-lg transition"
    >
      🐶 Animal Classifier
    </a>
    <a
      href="{% url 'vehicle_classifier:predict_vehicle' %}"
      class="p-4 bg-white rounded shadow hover:shadow-lg transition"
    >
      🚗 Vehicle Classifier
    </a>
    <a
      href="{% url 'human_emotion_classifier:predict_human_emotion' %}"
      class="p-4 bg-white rounded shadow hover:shadow-lg transition"
    >
      😊 Human Emotion Classifier
    </a>
    <a
      href="{% url 'digit_classifier:predict_digit' %}"
      class="p-4 bg-white rounded shadow hover:shadow-lg transition"
    >
      🔢 Digit Classifier
    </a>
  </div>
</div>
{% endblock %}